version: "3.8"

services:
  postgres:
    build:
      context: ./postgresql
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow_job:
    build:
      context: ./airflow_job  # airflow_job 폴더에서 Dockerfile을 사용
      dockerfile: Dockerfile
    container_name: airflow
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__WEBSERVER__RBAC: "True"
    ports:
      - "8080:8080"
    volumes:
      - ./airflow_job/dags:/opt/airflow/dags
      - ./airflow_job/logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./airflow_job/dbt:/opt/airflow/dbt
  jupyter:
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    container_name: jupyter-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter/notebooks:/home/jovyan/work
    environment:
      JUPYTER_ENABLE_LAB: "yes"  # JupyterLab 인터페이스 활성화
    depends_on:
      - postgres
volumes:
  postgres_data: